# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="random"
ZSH_THEME="nicoulaj"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

## from https://github.com/skwp/dotfiles/blob/master/zsh/zshrc


# # Give me my bash style incremental search
bindkey '^R' history-incremental-search-backward

# Speed up git completion
# http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () {
  _wanted files expl 'local files' _files
}

## end https://github.com/skwp/dotfiles/blob/master/zsh/zshrc

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/opt/local/bin:/opt/local/sbin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/usr/X11/bin:/usr/local/git/bin:/usr/local/share/npm/bin:/usr/local/sbin
[[ -s "$HOME/.nvm/nvm" ]] && source ~/.nvm/nvm.sh
[[ -s "$HOME/nvm/nvm" ]] && source ~/nvm/nvm.sh


compctl -g '~/.teamocil/*(:t:r)' teamocil

# Things I don't want to publish to github
[[ -s "$HOME/.secrets" ]] && source "$HOME/.secrets"
unsetopt correct_all
export TERM=xterm-256color tmux

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

function project()  {
  echo -ne "\e]1;$1\a" && tmuxinator $1
}

export EDITOR='vim'

PATH=/usr/local/mysql/bin:$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"
alias mochac='mocha --compilers coffee:coffee-script'
export NODE_PATH=/usr/local/lib/node_modules
alias brick='cd ~/dev/work/brickftp/'
source ~/.nvm/nvm.sh
export RBENV_VERSION=
export SPEC_OPTS="--color"
alias homefish-prod='ssh -i ~/.ssh/pair-programming.pem ubuntu@54.204.27.235'
export PATH=/usr/local/php5/bin:$PATH

alias c pbcopy
alias v pbpaste

file-to-clipboard() {
    osascript \
        -e 'on run args' \
        -e 'set the clipboard to POSIX file (first item of args)' \
        -e end \
        "$@"
}


[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

export RBENV_VERSION=

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# android config 
export PATH=$PATH:$HOME/android/sdk/platform-tools/:$HOME/android/sdk/tools/
